In [2]:
# imports
import pandas as pd

In [2]:
HGMD_lofgof_df = pd.read_csv('/Users/sayehkohani/Data/goflof_HGMD2019_v032021.csv')
ClinVar_lofgof_df = pd.read_csv('/Users/sayehkohani/Data/goflof_ClinVar_v062021.csv')

In [3]:
#Isolate all GOF 
HGMD_gof_df = HGMD_lofgof_df.loc[HGMD_lofgof_df['LABEL'] == 'GOF']
ClinVar_gof_df = ClinVar_lofgof_df.loc[ClinVar_lofgof_df['LABEL'] == 'GOF']

In [4]:
HGMD_gof_df.to_csv('/Users/sayehkohani/Dropbox/Research/Sanders_Lab/GoF/Output/All_GOF_HGMD.txt', sep='\t')
ClinVar_gof_df.to_csv('/Users/sayehkohani/Dropbox/Research/Sanders_Lab/GoF/Output/All_GOF_ClinVar.txt', sep='\t')

In [25]:
# Calculate number of appearing GOF variants per gene
gof_per_gene_HGMD_dict = HGMD_gof_df['GENE'].value_counts().to_dict()
gof_per_gene_ClinVar_dict = ClinVar_gof_df['GeneSymbol'].value_counts().to_dict()

In [29]:
gof_per_gene_HGMD_df = pd.DataFrame(list(gof_per_gene_HGMD_dict.items()), columns = ['GENE','#GOF'])
gof_per_gene_ClinVar_df = pd.DataFrame(list(gof_per_gene_ClinVar_dict.items()), columns = ['GENE','#GOF'])

In [31]:
# save

gof_per_gene_ClinVar_df.to_excel('/Users/sayehkohani/Dropbox/Research/Sanders_Lab/GoF/Output/GOF_Per_Gene_ClinVar.xlsx')
gof_per_gene_HGMD_df.to_excel('/Users/sayehkohani/Dropbox/Research/Sanders_Lab/GoF/Output/GOF_Per_Gene_HGMD.xlsx')

In [35]:
# Merge ClinVar and HGMD data

gof_per_gene_ClinVar_HGMD_df = pd.merge(gof_per_gene_HGMD_df, gof_per_gene_ClinVar_df, how = 'outer', on = 'GENE', suffixes=('_HGMD', '_ClinVar'))
gof_per_gene_ClinVar_HGMD_df

                    GENE  #GOF_HGMD  #GOF_ClinVar
0                  STAT1       33.0           8.0
1                 PTPN11       31.0          13.0
2                  SCN9A       31.0          20.0
3                   SOS1       23.0          12.0
4                   SOD1       22.0          14.0
..                   ...        ...           ...
238               STING1        NaN           2.0
239  GUCA1A;LOC118142757        NaN           1.0
240            HRC;TRPM4        NaN           1.0
241               CFB;C2        NaN           1.0
242                RTEL1        NaN           1.0

[243 rows x 3 columns]

In [37]:
gof_per_gene_ClinVar_HGMD_df.to_excel('/Users/sayehkohani/Dropbox/Research/Sanders_Lab/GoF/Output/GOF_Per_Gene_HGMD_ClinVar.xlsx')

In [3]:
## ADDING NDD PANEL GENE DATA 
import pandas as pd

NDD_panel_df = pd.read_excel('/Users/sayehkohani/Data/GOF/NDD_Panel_genes_freq.xlsx')

In [5]:
sub_NDD_panel_df = pd.DataFrame({
    'Gene': NDD_panel_df['Gene'],
    'asd.dn.ptv': NDD_panel_df['asd.dn.ptv'],
    'asd.dn.misa': NDD_panel_df['asd.dn.misa'],
    'asd.dn.misb': NDD_panel_df['asd.dn.misb'],
    'asd.case.ptv': NDD_panel_df['asd.case.ptv'],
    'asd.control.ptv': NDD_panel_df['asd.control.ptv'],
    'ddd.dn.ptv': NDD_panel_df['ddd.dn.ptv'],
    'ddd.dn.mis': NDD_panel_df['ddd.dn.mis']
})

In [6]:
sub_NDD_panel_df

,Gene,asd.dn.ptv,asd.dn.misa,asd.dn.misb,asd.case.ptv,asd.control.ptv,ddd.dn.ptv,ddd.dn.mis
0,ACADVL,0,0,0,1,1,0,1
1,ANO5,1,0,0,5,8,0,4
2,BAG3,0,0,0,0,0,0,6
3,CAPN3,0,0,0,0,2,0,0
4,CAV3,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...
2995,PEX11A,0,0,0,0,1,0,0
2996,CHCHD2,0,0,0,0,0,0,1
2997,IPPK,0,0,0,0,0,0,0
2998,SLC41A1,0,0,0,0,0,0,1
2999,SNCAIP,0,0,0,0,1,0,2

In [12]:
top_gof_df = pd.read_excel('/Users/sayehkohani/Dropbox/Research/Sanders_Lab/GoF/Output/Annotated_GOF_Per_Gene_HGMD_ClinVar.xlsx',index_col=0)

In [13]:
top_gof_df

,GENE,#GOF_HGMD,#GOF_ClinVar,NDD_664_Fu,Disorder,Neurodev.
0,STAT1,33.0,8.0,Y,Immunodeficiency,N
1,PTPN11,31.0,13.0,Y,Noonan's,Y
2,SCN9A,31.0,20.0,N,Paroxysmal extreme pain disorder,N
3,SOS1,23.0,12.0,Y,Noonan's,Y
4,SOD1,22.0,14.0,N,ALS,N
...,...,...,...,...,...,...
238,STING1,NaN,2.0,N,NaN,NaN
239,GUCA1A;LOC118142757,NaN,1.0,N,NaN,NaN
240,HRC;TRPM4,NaN,1.0,N,NaN,NaN
241,CFB;C2,NaN,1.0,N,NaN,NaN
242,RTEL1,NaN,1.0,N,NaN,NaN

In [14]:
merged_df = pd.merge(top_gof_df, sub_NDD_panel_df, left_on = 'GENE', right_on = 'Gene', how = 'left')

In [19]:
merged_df.to_excel('/Users/sayehkohani/Dropbox/Research/Sanders_Lab/GoF/Output/Annotated_GOF_Per_Gene_HGMD_ClinVar.xlsx')