In [12]:
import pandas as pd
import gzip

In [10]:
column_names = ['Var_ID_hg38', 'Gencode_ID', 'Gene_Symbol', 'Var_Type']
bamovar_df = pd.read_csv('/Users/sayehkohani/Data/GOF/BamoVar/extracted_columns_varid.txt', sep = '\t', names=column_names)

In [11]:
bamovar_df.head()

      Var_ID_hg38         Gencode_ID Gene_Symbol          Var_Type
0  chr1:65568:A:C  ENSG00000186092.7       OR4F5  missense_variant
1  chr1:65568:A:G  ENSG00000186092.7       OR4F5  missense_variant
2  chr1:65569:A:C  ENSG00000186092.7       OR4F5  missense_variant
3  chr1:65569:A:G  ENSG00000186092.7       OR4F5  missense_variant
4  chr1:65569:A:T  ENSG00000186092.7       OR4F5  missense_variant

In [13]:
logofunc_predictions_file = gzip.open('/Users/sayehkohani/Data/GOF/logofunc-predictions-main/LoGoFunc_preds_SK_updated.csv.gz', 'rt')

In [15]:
logofunc_predictions_df = pd.read_csv(logofunc_predictions_file, sep='\t', header = 0)

In [16]:
logofunc_predictions_df.head()

,Chr,Pos_hg19,REF,ALT,Var_ID_hg19,prediction,LoGoFunc_neutral,LoGoFunc_GOF,LoGoFunc_LOF,Coord
0,chr1,65568,A,C,chr1:65568:A:C,LOF,0.300530,0.101880,0.597590,chr1 65568 65568
1,chr1,65568,A,G,chr1:65568:A:G,LOF,0.310096,0.094875,0.595029,chr1 65568 65568
2,chr1,65569,A,C,chr1:65569:A:C,LOF,0.379354,0.089875,0.530770,chr1 65569 65569
3,chr1,65569,A,G,chr1:65569:A:G,LOF,0.383311,0.095775,0.520913,chr1 65569 65569
4,chr1,65569,A,T,chr1:65569:A:T,LOF,0.368772,0.089618,0.541610,chr1 65569 65569

In [17]:
logofunc_predictions_df = logofunc_predictions_df.drop('Coord', axis = 1)

In [19]:
column_name_mapping = {
    'Pos_hg19': 'Pos_hg38',
    'Var_ID_hg19': 'Var_ID_hg38',
    # Add more columns as needed
}

logofunc_predictions_df = logofunc_predictions_df.rename(columns = column_name_mapping)

In [21]:
logofunc_predictions_df.head()

,Chr,Pos_hg38,REF,ALT,Var_ID_hg38,prediction,LoGoFunc_neutral,LoGoFunc_GOF,LoGoFunc_LOF
0,chr1,65568,A,C,chr1:65568:A:C,LOF,0.300530,0.101880,0.597590
1,chr1,65568,A,G,chr1:65568:A:G,LOF,0.310096,0.094875,0.595029
2,chr1,65569,A,C,chr1:65569:A:C,LOF,0.379354,0.089875,0.530770
3,chr1,65569,A,G,chr1:65569:A:G,LOF,0.383311,0.095775,0.520913
4,chr1,65569,A,T,chr1:65569:A:T,LOF,0.368772,0.089618,0.541610

In [22]:
logofunc_predictions_bamovar = pd.merge(logofunc_predictions_df, bamovar_df, how = 'left', on = 'Var_ID_hg38')

In [23]:
logofunc_predictions_bamovar.head()

,Chr,Pos_hg38,REF,ALT,Var_ID_hg38,prediction,LoGoFunc_neutral,LoGoFunc_GOF,LoGoFunc_LOF,Gencode_ID,Gene_Symbol,Var_Type
0,chr1,65568,A,C,chr1:65568:A:C,LOF,0.300530,0.101880,0.597590,ENSG00000186092.7,OR4F5,missense_variant
1,chr1,65568,A,G,chr1:65568:A:G,LOF,0.310096,0.094875,0.595029,ENSG00000186092.7,OR4F5,missense_variant
2,chr1,65569,A,C,chr1:65569:A:C,LOF,0.379354,0.089875,0.530770,ENSG00000186092.7,OR4F5,missense_variant
3,chr1,65569,A,G,chr1:65569:A:G,LOF,0.383311,0.095775,0.520913,ENSG00000186092.7,OR4F5,missense_variant
4,chr1,65569,A,T,chr1:65569:A:T,LOF,0.368772,0.089618,0.541610,ENSG00000186092.7,OR4F5,missense_variant

In [24]:
desired_column_order = ['Chr', 'Pos_hg38', 'REF', 'ALT', 'Var_ID_hg38', 'Gencode_ID', 'Gene_Symbol','Var_Type', 'prediction','LoGoFunc_neutral','LoGoFunc_GOF','LoGoFunc_LOF']
logofunc_predictions_bamovar = logofunc_predictions_bamovar[desired_column_order]

In [25]:
logofunc_predictions_bamovar.head()

,Chr,Pos_hg38,REF,ALT,Var_ID_hg38,Gencode_ID,Gene_Symbol,Var_Type,prediction,LoGoFunc_neutral,LoGoFunc_GOF,LoGoFunc_LOF
0,chr1,65568,A,C,chr1:65568:A:C,ENSG00000186092.7,OR4F5,missense_variant,LOF,0.300530,0.101880,0.597590
1,chr1,65568,A,G,chr1:65568:A:G,ENSG00000186092.7,OR4F5,missense_variant,LOF,0.310096,0.094875,0.595029
2,chr1,65569,A,C,chr1:65569:A:C,ENSG00000186092.7,OR4F5,missense_variant,LOF,0.379354,0.089875,0.530770
3,chr1,65569,A,G,chr1:65569:A:G,ENSG00000186092.7,OR4F5,missense_variant,LOF,0.383311,0.095775,0.520913
4,chr1,65569,A,T,chr1:65569:A:T,ENSG00000186092.7,OR4F5,missense_variant,LOF,0.368772,0.089618,0.541610

In [26]:
# Save logofunc_bamovar_annotated file
logofunc_predictions_bamovar.to_csv('/Users/sayehkohani/Data/GOF/logofunc-predictions-main/LoGoFunc_preds_SK_bamovar.csv.gz', sep = '\t', index=False, compression='gzip')

## Isolate all GOF

In [27]:
all_gof_df = logofunc_predictions_bamovar[logofunc_predictions_bamovar['prediction'] == 'GOF']

In [29]:
# Find top genes
gof_per_gene_dict = all_gof_df['Gene_Symbol'].value_counts().to_dict()
gof_per_gene_df = pd.DataFrame(list(gof_per_gene_dict.items()), columns = ['Gene','#GOF_LoGoFunc'])

In [30]:
gof_per_gene_df

         Gene  #GOF_LoGoFunc
0        RYR2          31284
1        RYR1          26392
2       MACF1          22239
3      CELSR3          20820
4      CELSR1          19727
...       ...            ...
6786    WASF3              1
6787     PHIP              1
6788  SLCO4A1              1
6789    PPIL6              1
6790    CDY1B              1

[6791 rows x 2 columns]

In [33]:
gof_per_gene_df.to_csv('/Users/sayehkohani/Dropbox/Research/Sanders_Lab/GoF/Output/All_GOF_LoGoFunc.txt', sep = '\t')

In [40]:
# Merge with the annotated file

annotated_all_gof = pd.read_excel('/Users/sayehkohani/Dropbox/Research/Sanders_Lab/GoF/Output/Annotated_GOF_Per_Gene_HGMD_ClinVar.xlsx')

In [41]:
annotated_all_gof.head()

,Gene,#GOF_HGMD,#GOF_ClinVar,NDD_664_Fu,asd.dn.ptv,asd.dn.misa,asd.dn.misb,asd.case.ptv,asd.control.ptv,ddd.dn.ptv,ddd.dn.mis,GOF-Associated Disorder,Neurodev.
0,STAT1,33.0,8.0,Y,0,0,0,1,0,0.0,5.0,Immunodeficiency,Y
1,PTPN11,31.0,13.0,Y,0,0,1,0,0,0.0,62.0,Noonan's,Y
2,SCN9A,31.0,20.0,N,0,0,0,0,0,2.0,3.0,Paroxysmal extreme pain disorder,N
3,SOS1,23.0,12.0,Y,0,0,0,0,0,1.0,11.0,Noonan's,Y
4,SOD1,22.0,14.0,N,0,0,0,0,0,0.0,1.0,ALS,N

In [47]:
merged_all_gof = pd.merge(gof_per_gene_df, annotated_all_gof, on = 'Gene', how = 'outer')

In [48]:
merged_all_gof

,Gene,#GOF_LoGoFunc,#GOF_HGMD,#GOF_ClinVar,NDD_664_Fu,asd.dn.ptv,asd.dn.misa,asd.dn.misb,asd.case.ptv,asd.control.ptv,ddd.dn.ptv,ddd.dn.mis,GOF-Associated Disorder,Neurodev.
0,RYR2,31284.0,4.0,3.0,Y,1,1,0,0,1,0.0,21.0,Ventricular tachycardia,N(?)
1,RYR1,26392.0,1.0,NaN,N,0,3,0,0,1,1.0,22.0,NaN,NaN
2,MACF1,22239.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CELSR3,20820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CELSR1,19727.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6792,TMEM173,NaN,2.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6793,FIBP,NaN,1.0,1.0,N,0,0,0,0,0,0.0,2.0,NaN,NaN
6794,GUCA1A;LOC118142757,NaN,NaN,1.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6795,HRC;TRPM4,NaN,NaN,1.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6796,CFB;C2,NaN,NaN,1.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
merged_all_gof.to_csv('/Users/sayehkohani/Dropbox/Research/Sanders_Lab/GoF/Output/Annotated_GOF_Per_Gene_All.txt', sep = '\t', index=False)

In [56]:
# Adding Fu_NDD664 Data

combo_gene_df = pd.read_csv('/Users/sayehkohani/Data/Reference Databases/Combo_Genes/ref_combo_genes_panel_gnomAD_omim_hpo1_hpo2_hpo3_asd.txt', sep = '\t')
ASD_df = pd.DataFrame({
    'Gene': combo_gene_df['Gene_symbol'],
    'NDD_664_Fu': combo_gene_df['Fu_NDD664']
})

In [58]:
merged_all_gof_fu = pd.merge(merged_all_gof, ASD_df, how = 'left', on = 'Gene')

In [59]:
merged_all_gof_fu

,Gene,#GOF_LoGoFunc,#GOF_HGMD,#GOF_ClinVar,NDD_664_Fu_x,asd.dn.ptv,asd.dn.misa,asd.dn.misb,asd.case.ptv,asd.control.ptv,ddd.dn.ptv,ddd.dn.mis,GOF-Associated Disorder,Neurodev.,NDD_664_Fu_y
0,RYR2,31284.0,4.0,3.0,Y,1,1,0,0,1,0.0,21.0,Ventricular tachycardia,N(?),1
1,RYR1,26392.0,1.0,NaN,N,0,3,0,0,1,1.0,22.0,NaN,NaN,0
2,MACF1,22239.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,CELSR3,20820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,CELSR1,19727.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6803,TMEM173,NaN,2.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6804,FIBP,NaN,1.0,1.0,N,0,0,0,0,0,0.0,2.0,NaN,NaN,0
6805,GUCA1A;LOC118142757,NaN,NaN,1.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6806,HRC;TRPM4,NaN,NaN,1.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6807,CFB;C2,NaN,NaN,1.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
# Adding NDD Panel Data

NDD_panel_df = pd.read_excel('/Users/sayehkohani/Data/Reference Databases/NDD_Panel_genes_freq.xlsx')
sub_NDD_panel_df = pd.DataFrame({
    'Gene': NDD_panel_df['Gene'],
    'asd.dn.ptv': NDD_panel_df['asd.dn.ptv'],
    'asd.dn.misa': NDD_panel_df['asd.dn.misa'],
    'asd.dn.misb': NDD_panel_df['asd.dn.misb'],
    'asd.case.ptv': NDD_panel_df['asd.case.ptv'],
    'asd.control.ptv': NDD_panel_df['asd.control.ptv'],
    'ddd.dn.ptv': NDD_panel_df['ddd.dn.ptv'],
    'ddd.dn.mis': NDD_panel_df['ddd.dn.mis']
})

In [62]:
sub_NDD_panel_df.head()

,Gene,asd.dn.ptv,asd.dn.misa,asd.dn.misb,asd.case.ptv,asd.control.ptv,ddd.dn.ptv,ddd.dn.mis
0,ACADVL,0,0,0,1,1,0,1
1,ANO5,1,0,0,5,8,0,4
2,BAG3,0,0,0,0,0,0,6
3,CAPN3,0,0,0,0,2,0,0
4,CAV3,0,0,0,1,0,0,0

In [63]:
merged_all_gof_fu_NDD = pd.merge(merged_all_gof_fu, sub_NDD_panel_df, on = 'Gene', how = 'left')

In [64]:
merged_all_gof_fu_NDD.head()

,Gene,#GOF_LoGoFunc,#GOF_HGMD,#GOF_ClinVar,NDD_664_Fu_x,asd.dn.ptv_x,asd.dn.misa_x,asd.dn.misb_x,asd.case.ptv_x,asd.control.ptv_x,ddd.dn.ptv_x,ddd.dn.mis_x,GOF-Associated Disorder,Neurodev.,NDD_664_Fu_y,asd.dn.ptv_y,asd.dn.misa_y,asd.dn.misb_y,asd.case.ptv_y,asd.control.ptv_y,ddd.dn.ptv_y,ddd.dn.mis_y
0,RYR2,31284.0,4.0,3.0,Y,1,1,0,0,1,0.0,21.0,Ventricular tachycardia,N(?),1,1,1,0,0,1,0,21
1,RYR1,26392.0,1.0,NaN,N,0,3,0,0,1,1.0,22.0,NaN,NaN,0,0,3,0,0,1,1,22
2,MACF1,22239.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,2,2,0,7
3,CELSR3,20820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CELSR1,19727.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
merged_all_gof_fu_NDD.to_csv('/Users/sayehkohani/Dropbox/Research/Sanders_Lab/GoF/Output/Annotated_GOF_Per_Gene_All_Fu_NDD.txt', sep = '\t', index=False)

## Identify Data Specs

In [31]:
# Find percentage of each prediction

# Calculate value counts
value_counts = logofunc_predictions_bamovar['prediction'].value_counts()

# Calculate percentages
total_count = value_counts.sum()
percentages = (value_counts / total_count) * 100

print(percentages)

Neutral    69.579856
LOF        25.901027
GOF         4.519117
Name: prediction, dtype: float64

In [32]:
# Find percentage of each var_type

# Calculate value counts
value_counts = logofunc_predictions_bamovar['Var_Type'].value_counts()

# Calculate percentages
total_count = value_counts.sum()
percentages = (value_counts / total_count) * 100

print(percentages)

missense_variant                        98.429206
stop_gained                              0.620996
stop_lost                                0.548527
start_lost                               0.087771
splice_acceptor_variant                  0.057581
5_prime_UTR_variant                      0.052715
non_coding_transcript_exon_variant       0.049904
splice_donor_variant                     0.036863
promoter_region_variant                  0.032668
synonymous_variant                       0.024122
3_prime_UTR_variant                      0.013761
incomplete_terminal_codon_variant        0.013756
intron_variant                           0.013151
intergenic                               0.009768
splice_unrecognized_donor_variant        0.005644
splice_region_variant                    0.002357
splice_unrecognized_acceptor_variant     0.000556
stop_retained_variant                    0.000347
splice_minor_acceptor_variant            0.000259
splice_minor_donor_variant               0.000039
start_retained_variant                   0.000012
Name: Var_Type, dtype: float64